version: '3'

services:
  operatingpro:
    build:
      context: .
      dockerfile: Dockerfile
    image: operatingpro
    container_name: operatingpro
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"