export const serverKeys = {
    candidateMe: "candidateMe",
    companyMe: "companyMe",
    jobPostList: "jobPostList",
    jobPostListCandidate: "jobPostListCandidate",
    jobPostRecommendedListCandidate: "jobPostRecommendedListCandidate",
    jobPostListByCompany: "jobPostListByCompany",
    jobPostGetById: "jobPostGetById",
    jobApplicationListByCandidate: "jobApplicationListByCandidate",
    jobApplicationListByCompanyAndJob: "jobApplicationListByCompanyAndJob",
    jobApplicationListByJob: "jobApplicationListByJob",
    candidateList: "candidateList",
    candidateById: "candidateById",
    companyById: "companyById",
    companyList: "companyList",
}